language: node_js
cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
node_js:
  - "11"
script:
  - sudo ln -s $(which node) /usr/bin/node
  - npm run percy-cypress-app:ci
  # to kill all background jobs (like "npm start")
  - kill $(jobs -p) || true
